#!/bin/bash
#
#  Copyright (c) 2017, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -euxo pipefail

install_packages()
{
    sudo apt-get update

    sudo apt-get install --no-install-recommends -y \
        build-essential \
        ninja-build \
        libdbus-1-dev \
        libreadline-dev \
        libncurses-dev

    # OpenThread requires CMake 3.11.4 or later
    sudo apt-get install -y --no-install-recommends python3-pip
    sudo pip3 install -U scikit-build
    sudo pip3 install --system -U cmake

    # OpenThread Border Agent supprots both avahi and mDNSResponder
    (
        cd /tmp
        MDNS_SOURCE_NAME=mDNSResponder-878.30.4
        wget https://opensource.apple.com/tarballs/mDNSResponder/$MDNS_SOURCE_NAME.tar.gz
        tar xvf $MDNS_SOURCE_NAME.tar.gz
        cd $MDNS_SOURCE_NAME/mDNSPosix
        make os=linux && sudo make install os=linux
    )
}

install_openthread()
{
    local otbr_options=(
        "-DBUILD_TESTING=OFF"
        "-DCMAKE_INSTALL_PREFIX=/usr"
        "-DOTBR_DBUS=ON"
        "-DOTBR_MDNS=mDNSResponder"
    )

    git submodule update --init --recursive --depth 1

    mkdir -p build
    cd build
    cmake -GNinja .. "${otbr_options[@]}"
    ninja
    sudo ninja install
}

main()
{
    install_packages
    install_openthread
}

main
